stages:
  - deploy

repoupdate:
  stage: deploy
  before_script:
    - apt update --yes
    - apt install twine python3-setuptools python3-build python3-venv --yes
  script:
    - python3 -m venv venv
    - ./venv/bin/pip install build twine
    - ./venv/bin/python -m build
    - ./venv/bin/twine upload dist/*
  tags:
    - debian
  only:
    - tags